#!/bin/zsh

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

# backup prompt
PROMPT='[%n@%m %1~] $ '
PROMPT2='> '

# source profiles from /etc/shellrc.d
if test -d /etc/shellrc.d/; then
    for scr in /etc/shellrc.d/*.sh; do
        test -r "$scr" && source "$scr"
    done
    unset scr
fi
