#!/bin/bash

#------------------------------------------------------------------#
# File:     environment.sh    Environment variables                #
# Version:                                                         #
# Author:   Abdó Roig-Maranges <abdo.roig@gmail.com>               #
#------------------------------------------------------------------#

function add_to_pathlist_left () {
   local cl=$1
   local item=$2
   local cl_content

   eval "cl_content=\$$cl"
   if [[ -d $item ]]; then
      case ":$cl_content:" in
          *":$item:"*) ;;           # already there
          *) eval "$cl=$item:\$$cl" ;;
      esac
   fi
}



#------------------------------
# Some software
#------------------------------

export EDITOR=vim                        # default editor
export EMACS="emacsclient -c -a emacs"   # emacs
export BROWSER=chromium                  # default browser
export PAGER=vimpager                    # wrapper for vim
export TERMCMD=urxvt                     # terminal
export SHELL=zsh


#------------------------------
# Development environment
#------------------------------

export CC="colorgcc"


#------------------------------
# Application variables
#------------------------------

SAGE_KEEP_BUILT_SPKGS=yes    # don't rebuild from scratch


#------------------------------
# Paths
#------------------------------

# Path to the wiki
export WIKI="$HOME/Work/wiki"

# These are a personal things for my code
export BASHPATH="$HOME/Software/libs/bash"

# Lua path for for personal libs
export LUA_PATH="$HOME/Software/libs/lua/?.lua;;"
export LUA_CPATH="$HOME/Software/libs/lua/?.lua;;"

# Python
export PYTHONDOCS=/usr/share/docs/python/html/

# My local terminfo
if [[ -d $HOME/.terminfo ]]; then
    export TERMINFO="$HOME/.terminfo:/usr/share/terminfo"
fi

# The path
add_to_pathlist_left PATH "$HOME/bin"
export PATH
