#!/bin/bash

# Source environment
source $HOME/.environment
source $HOME/.aliases

# Variables
host=$(hostname -s)

# Run system xinitrc stuff
if [ -d /etc/X11/xinit/xinitrc.d ]; then
    for f in /etc/X11/xinit/xinitrc.d/*; do
        [ -x "$f" ] && . "$f"
    done
    unset f
fi


# host specific settings
case $host in    
    galois)
        xbacklight -set 15           # set backlight
        asym screen single           # set screen mode
        
        rfkill block bluetooth       # kill all radios but wifi
        rfkill block wimax
        rfkill block wwan
        ;;
    
    grothendieck)
        numlockx on                  # enable numlock
        asym screen xinerama         # set screen mode
        asym bamboo 1 &              # setup bamboo for first screen
        
#        killall cairo-compmgr        # cairo-compmgr compositor
#        cairo-compmgr -n &           
        ;;   
    
    *)
        numlockx on                  # enable numlock
        asym screen single           # set screen mode
        
#        killall cairo-compmgr        # cairo-compmgr compositor
#        cairo-compmgr -n &           
        ;;   
esac    

case "$1" in
    gnome)     unit=gnome.target       ;;   
    awesome)   unit=awesome.target     ;; 
    openbox)   unit=openbox.target     ;;
    xmonad)    uniy=xmonad.target      ;;
    *)         unit=wm.target          ;;
esac

# User systemd daemon
/usr/lib/systemd/systemd --user --unit=default.target


