#!/bin/bash

#------------------------------------------------------------------#
# File:     environment.sh    Environment variables                #
# Version:                                                         #
# Author:   Abdó Roig-Maranges <abdo.roig@gmail.com>               #
#------------------------------------------------------------------#

#------------------------------------------------------------------#
# NOTE:                                                            #
# In order to export the environment to the systemd --user         #
# session this file gets parsed by a shell script. So keep it      #
# in a clean format with lines like                                #
# export VAR=value                                                 #
#------------------------------------------------------------------#


function add_to_pathlist_left () {
   local cl="$1"
   local item="$2"
   local cl_content

   eval "cl_content=\$$cl"
   case ":$cl_content:" in
       *":$item:"*)                    ;;       # already there
       *) eval "$cl=$item:$cl_content" ;;
   esac
}


#------------------------------
# Some software
#------------------------------

export EMACS="$HOME/bin/emacs-client"                   # emacs
export EDITOR="/usr/bin/vim"                            # default editor
export ALTERNATE_EDITOR="/usr/bin/emacs"                # emacsclient uses this if can't find server

export BROWSER="/usr/bin/chromium"                      # default browser
export FILEMANAGER="/usr/bin/thunar"                    # the file manager
export DIFFPROG="$HOME/bin/emacs-diff"                  # tool to display diffs
export PAGER="/usr/bin/vimpager"                        # wrapper for vim
export TERMCMD="/usr/bin/termite"                       # terminal
export SHELL="/bin/zsh"

# disable pager by default on systemd
export SYSTEMD_PAGER="cat"



#------------------------------
# Sockets
#------------------------------

# gpg-agent sockets. Those sockets are proxied for socket activation!
export SSH_AUTH_SOCK="$HOME/.gnupg/S.gpg-agent.ssh"
export GPG_AGENT_INFO="$HOME/.gnupg/S.gpg-agent::1"

# mpd socket
export MPD_HOST="$XDG_RUNTIME_DIR/mpd/mpd.socket"

# screen socket
export SCREENDIR="$XDG_RUNTIME_DIR/screen"



#------------------------------
# Development environment
#------------------------------

# Default C/C++ compiler
export CC=gcc
export CXX=g++

# Mingw
export MINGW_ROOT="/usr/x86_64-w64-mingw32"



# Java development
export JAVA_HOME="/usr/lib/jvm/default"

# Android variables for the toolchain
export ANDROID_NDK_ROOT="/opt/android-ndk"    # root for NDK (understood upstream)
export ANDROID_SDK_ROOT="/opt/android-sdk"    # root for SDK (understood upstream)
export ANDROID_LIBS_ROOT="/opt/android-libs"  # root for custom libs (just mine)

# Android SDK wants to set this
export ANDROID_HOME="/opt/android-sdk"
export ANDROID_SWT="/usr/share/java"


#------------------------------
# Application variables
#------------------------------

# gtk
# disable accessibility for GTK3 apps
# https://forums.gentoo.org/viewtopic-p-7380668.html?sid=265ddf475643bf5c86fe72440cf6cbe8
# export NO_AT_BRIDGE=1 

# ranger
export RANGER_LOAD_DEFAULT_RC=FALSE

# java
export _JAVA_OPTIONS='-Dawt.useSystemAAFontSettings=on -Dswing.aatext=true -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true'

# QT5 style
export QT_STYLE_OVERRIDE=gtk

# nix uses this
export SSL_CERT_FILE="/etc/ssl/certs/ca-certificates.crt"



#------------------------------
# Paths
#------------------------------

# Python
export PYTHONDOCS="/usr/share/docs/python/html/"

# My local terminfo
export TERMINFO="$HOME/.terminfo:/usr/share/terminfo"

# cdpath
# export CDPATH=""

# The path
add_to_pathlist_left PATH "$HOME/bin"
export PATH="$PATH"
