"---------------------------------------------------------------------"
" File:   /etc/vimrc                                                  "
" Author: Abdó Roig-Maranges <abdo.roig@gmail.com                     "
" Desc:   global vim configuration                                    "
"---------------------------------------------------------------------"

" All system-wide defaults are set in $VIMRUNTIME/archlinux.vim (usually just
" /usr/share/vim/vimfiles/archlinux.vim) and sourced by the call to :runtime
" you can find below.  If you wish to change any of those settings, you should
" do it in this file (/etc/vimrc), since archlinux.vim will be overwritten
" everytime an upgrade of the vim packages is performed.  It is recommended to
" make changes after sourcing archlinux.vim since it alters the value of the
" 'compatible' option.

" This line should not be removed as it ensures that various options are
" properly set to work with the Vim-related packages.
runtime! archlinux.vim

" If you prefer the old-style vim functionalty, add 'runtime! vimrc_example.vim'
" Or better yet, read /usr/share/vim/vim74/vimrc_example.vim or the vim manual
" and configure vim to your own liking!


" Configuration
" --------------------

source /etc/vimrc.d/general.vim
source /etc/vimrc.d/keymaps.vim
source /etc/vimrc.d/ui.vim


" Diff mode
" --------------------

" diff mode
if &diff
    syntax off
    nmap N [c
    nmap n ]c
    nmap d< :diffget LOCAL<cr>
    nmap d> :diffget REMOTE<cr>
    nmap d^ :diffget BASE<cr>
endif


" Display
" --------------------

" enable cursor line on active window
augroup ActiveWindowCursorLine
  autocmd!
  autocmd VimEnter,WinEnter,BufWinEnter * setlocal cursorline
  autocmd WinLeave * setlocal nocursorline
augroup END
