"---------------------------------------------------------------------"
" File:   /etc/vimrc                                                  "
" Author: Abdó Roig-Maranges <abdo.roig@gmail.com                     "
" Desc:   global vim configuration                                    "
"---------------------------------------------------------------------"

" All system-wide defaults are set in $VIMRUNTIME/archlinux.vim (usually just
" /usr/share/vim/vimfiles/archlinux.vim) and sourced by the call to :runtime
" you can find below.  If you wish to change any of those settings, you should
" do it in this file (/etc/vimrc), since archlinux.vim will be overwritten
" everytime an upgrade of the vim packages is performed.  It is recommended to
" make changes after sourcing archlinux.vim since it alters the value of the
" 'compatible' option.

" This line should not be removed as it ensures that various options are
" properly set to work with the Vim-related packages.
runtime! archlinux.vim

" If you prefer the old-style vim functionalty, add 'runtime! vimrc_example.vim'
" Or better yet, read /usr/share/vim/vim74/vimrc_example.vim or the vim manual
" and configure vim to your own liking!


" General options
" --------------------
set nocompatible                  " vim defaults. forget about vi compatibility!

set hidden                        " Don't force to save files when switching
set confirm                       " confirm instead of fail when saving is needed
set history=700                   " lines of history to remember

filetype plugin on                " enable filetype pluginso
set autoread                      " reload a file when changed externally
set ffs=unix,dos,mac              " file type preference

syntax on                         " Enable syntax highlighting
set hlsearch                      " Highlight searches
set wildmenu                      " Better autocompletion
set showmatch                     " match parenthesis

set ignorecase                    " case insensitive searches
set smartcase

" quickly time out on keycodes, but never time out on mappings
set notimeout ttimeout ttimeoutlen=200

set backspace=indent,eol,start    " enhance backspace
set nostartofline                 " prevent some movements to go to start of line


" Text options
" --------------------
filetype indent plugin on         " Smart indenting
set autoindent                    " automatic indents
set shiftwidth=4
set softtabstop=4
set tabstop=4
set expandtab


" Latex Options
" --------------------
let g:tex_flavor = "latex"


" Bindings
" --------------------
" movement
map J 30j                         " movement by blocks of 30 lines
map K 30k

" diff mode
if &diff
    nmap N [c
    nmap n ]c
    nmap d< :diffget LOCAL<CR>
    nmap d> :diffget REMOTE<CR>
    nmap d^ :diffget BASE<CR>
endif

" vim internals
command SyntaxGroup echo synIDattr(synID(line("."),col("."),1),"name")


" User Interface
" --------------------
colors abdo                       " default color scheme
set background=dark               " dark background

set showcmd                       " show partial command
set laststatus=2                  " always display status line

"set ruler                         " show cursor position


" Status Line
" --------------------
function! StatuslineMode(m)
    let curm = toupper(mode())
    if a:m == curm
        return '[' . curm . ']'
    else
        return ''
    endif
endfunction

function! StatuslineFiletype()
    if &filetype != ''
        return &filetype . ' '
    else
        return ''
    endif
endfunction

function! StatuslineFormatoptions()
    if &formatoptions != ''
        return &formatoptions . ' '
    else
        return ''
    endif
endfunction

set statusline=

set statusline+=%#StatusLineInsert#%{StatuslineMode('I')}
set statusline+=%#StatusLineNormal#%{StatuslineMode('N')}
set statusline+=%#StatusLineReplace#%{StatuslineMode('R')}
set statusline+=%#StatusLineVisual#%{StatuslineMode('V')}
set statusline+=%*

"tail of the filename with flags 
set statusline+=\ %{StatuslineFiletype()}%{StatuslineFormatoptions()}\|
set statusline+=\ %t\ 
set statusline+=%M%R%*

"left/right separator
set statusline+=%=

"git status
set statusline+=%{fugitive#head()}\ 

set statusline+=\|\ %l:%-2c\ %P\                             "line:column percent
set statusline+=\|\ %{strlen(&fenc)?&fenc:'none'}\ %{&ff}\   "file encoding, file format


