"---------------------------------------------------------------------"
" File:   /etc/vimrc                                                  "
" Author: Abdó Roig-Maranges <abdo.roig@gmail.com                     "
" Desc:   global vim configuration                                    "
"---------------------------------------------------------------------"

" add /etc/vim to the runtime path
:set runtimepath+=/etc/vim
